### ISSUE TITLE
Will using a single version of fmt tool be a good idea?

### ISSUE THREAD

**Issue by leavelet** [casdoor/casdoor-rust-sdk#14]
I noticed that the workflow will use all fmt tools from stable, beta and nightly version. But cargo fmt tool will change from version to version, and the result may be variable. So will it be a good idea to just use a single version of fmt tool?

**Comment by hsluoyz** [comment]
@leavelet good point. We can fix the fmt tool to the stable version.

**Comment by hsluoyz** [comment]
@qianxi0410 can you work on this?

**Comment by qianxi0410** [comment]
EMM. This error is not caused by the FMT tool, in fact, you did not format:
```rust
let mut user_now = user!(name="tmp".to_owned());
```

it should be:
```rust
let mut user_now = user!(name = "tmp".to_owned());
```

**Comment by leavelet** [comment]
Maybe some setting went wrong on my own machine. let me take a look.

**Comment by qianxi0410** [comment]
My settings:

```json
  "rust-analyzer.checkOnSave.command": "clippy",
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer",
    "editor.formatOnSave": true
  },
```

FYI @leavelet

**Comment by hsluoyz** [comment]
After applying @qianxi0410 's suggestion, the PR has pass all CI checks. But I think it's still beneficial to reduce some unnecessary checks, currently 9 combinations: (win, mac, linux) x (stable, beta, nightly). it is not only slow in PR validation but also waste the CI minutes of the org limited by github. Any suggestions? @leavelet @qianxi0410 I think we can remove `nightly` at least?

![image](https://user-images.githubusercontent.com/3787410/176986472-73defb1c-34f7-476d-8def-03355009c097.png)

**Comment by leavelet** [comment]
I think maybe stable version on Linux is enough. So far all the code is platform independent, and if we don't use unstable feature, Rust will provide strong compatibility

**Comment by hsluoyz** [comment]
OK. @qianxi0410 I think we can keep 4: (windows, ubuntu) x (stable, beta)

**Comment by qianxi0410** [comment]
I'll do this later.

**Comment by leavelet** [comment]
And the tests may fail on GitHub as they can't run without a valid casdoor deployment.
Maybe we can use the casdoor demo for test, and tests should be reconfigured.

**Comment by hsluoyz** [comment]
@leavelet the demo site: https://door.casdoor.com/ could be used. It will be always online. It's a read-only site.
