### ISSUE TITLE
semantic-release is still not working

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-rust-sdk#16]
There's no releases after the PR merges:

![image](https://user-images.githubusercontent.com/3787410/176988315-22b31afd-60ba-4892-927b-0d663c38d2d7.png)

**Comment by hsluoyz** [comment]
@qianxi0410

**Comment by qianxi0410** [comment]
This is normal behavior. The trigger for a release is to push a new tag to the master branch. pr does not trigger this behavior.

**Comment by hsluoyz** [comment]
@qianxi0410 so this is not semantic-release. You can google for what semantic-release is. Here are also some examples of what semantic-release:

- https://github.com/casdoor/casdoor-go-sdk
- https://github.com/casbin/casbin-rs/releases

**Comment by qianxi0410** [comment]
I'm test on my repo now, seem work. I will submit a pr later to fix this.
