### ISSUE TITLE
 "tag" field of token's user object  disappear

### ISSUE THREAD

**Issue by nosou** [casdoor/casdoor-rust-sdk#29]
If leave user‘s tag field blank, token's user object return from server will not contain "tag" field. Why "homepage" field don't like it.
![企业微信截图_16750561498973](https://user-images.githubusercontent.com/23098033/215402336-a2e2f91a-95fb-4652-abec-1eddf7feed16.png)
![企业微信截图_16750580381088](https://user-images.githubusercontent.com/23098033/215402362-b0dc82b8-ea9d-4a63-bf74-bb342bd99858.png)

**Comment by hardywu** [comment]
I guess it's related to the #28 . As the current casdoor is returning a new reduced-size token, the current rust-sdk version is by more than a whole year outdated.

**Comment by hsluoyz** [comment]
Fixed, please use:

- Latest Casdoor v1.426.0+: https://github.com/casdoor/casdoor/releases/tag/v1.426.0
- Latest Casdoor Rust SDK v1.3.0+: https://github.com/casdoor/casdoor-rust-sdk
- Refer to the example code: https://github.com/casdoor/casdoor-rust-example
