### ISSUE TITLE
JWT parsing keeps failing due to InvalidKeyFormat error after invoking parse_jwt_token()

### ISSUE THREAD

**Issue by DoctorNigel** [casdoor/casdoor-rust-sdk#33]
I've been trying to set up a working example on localhost for nextjs oauth with rust on the backend. I'm using the casdoor-rust-sdk to fetch the signup/signin uri which mostly works but when I try to authorize and fetch the JWT token from the rust backend I'm constantly being reminded of the InvalidKeyFormat error despite my conf.toml file being correctly formed (as per rust-sdk-example project)

I triple checked that the pub_key from the certs page in the dashboard is correct along with the generated certificate being assigned to the test application.

Is this a bug or am I missing something. Been at it for 3 hours.
![Screenshot 2023-07-13 at 15 39 19](https://github.com/casdoor/casdoor-rust-sdk/assets/18449905/ac216b36-0600-4227-bd93-3705fe4c49d9)

**Comment by hsluoyz** [comment]
@DoctorNigel hi, can you help fix this CI issue first? https://github.com/casdoor/casdoor-rust-sdk/actions/runs/5546217874/jobs/10126182590

**Comment by koiho** [comment]
Hi, I'm experiencing the same error with axum integration

`pub async fn login(
    Extension(ctx): Extension<ContextData>,
) -> anyhow::Result<Json<Response<String>>, AppError> {
    let auth_service = AuthService::new(&ctx.coasdoor_config);

    let redirect_url = auth_service.get_signin_url("http://localhost:8080/callback".to_string());

    Ok(Json(Response::status("ok".to_string(), Some(redirect_url))))
}

pub async fn callback(
    Extension(ctx): Extension<ContextData>,
    Form(input): Form<LoginRequest>,
) -> anyhow::Result<Json<Response<CasdoorUser>>, AppError> {
    let auth_service = AuthService::new(&ctx.coasdoor_config);

    match auth_service.get_auth_token(input.code) {
        Ok(token) => match auth_service.parse_jwt_token(token) {
            Ok(user) => Ok(Json(Response {
                message: "ok".to_string(),
                data: Some(user),
            })),
            Err(e) => Ok(Json(Response::status(e.to_string(), None))),
        },
        Err(e) => Ok(Json(Response::status(e.to_string(), None))),
    }
}`

![bb739d3a9f176162379e51d3673926c](https://github.com/casdoor/casdoor-rust-sdk/assets/83646762/90e0751e-30f9-40ed-a6ba-13a85b6ef87f)
![a3c7a87f84569bfecb04336248bb6f5](https://github.com/casdoor/casdoor-rust-sdk/assets/83646762/6ade7008-1cd5-49fe-9237-c9ac3287a01a)

**Comment by hsluoyz** [comment]
Fixed, please use:

- Latest Casdoor v1.426.0+: https://github.com/casdoor/casdoor/releases/tag/v1.426.0
- Latest Casdoor Rust SDK v1.3.0+: https://github.com/casdoor/casdoor-rust-sdk
- Refer to the example code: https://github.com/casdoor/casdoor-rust-example
