### ISSUE TITLE
Setup GitHub Actions CI and semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-rust-sdk#6]
Like: https://github.com/casbin/casbin-rs

**Comment by hsluoyz** [comment]
@qianxi0410

**Comment by qianxi0410** [comment]
In order to pass CI, I plan to put all network request related tests into integration tests first, in fact, they should also be in integration tests, so that in CI, we can not run the tests in integration.

**Comment by hsluoyz** [comment]
@qianxi0410 OK
